// df.d.ts manifest generator.
//
// Produces a TypeScript declaration file that lists every available `df.*`
// callable for a given tenant: collection handles from registered mounts,
// crystallised tools (with their YAML-frontmatter description as JSDoc),
// and seed/tenant primitives (with intent + schema as JSDoc).
//
// Mirrors the pattern Cloudflare Code Mode uses: instead of advertising
// tools as JSON descriptors and routing each call through the model,
// expose them as a typed code surface the model writes against. The
// signatures are denser and the model's TypeScript training prior does
// the heavy lifting on what each function does.
//
// Regeneration is cheap and idempotent. Called from /v1/connect (so the
// manifest reflects the active workspace at session boot) and from the
// observer's authoring path (so a freshly-crystallised tool appears
// immediately in the manifest the next caller reads).

import { promises as fsp } from "node:fs";
import path from "node:path";

import { getMountRuntimeRegistry } from "../adapter/runtime.js";
import type { FnSpec } from "../sdk/index.js";
import { DiskLibraryResolver } from "../snippet/library.js";

// --- Public ----------------------------------------------------------------

export type RegenerateManifestOpts = {
  baseDir: string;
  tenantId: string;
};

// Write `<baseDir>/df.d.ts` reflecting the current workspace state.
// Best-effort: errors are swallowed and logged so a transient miss
// doesn't crash the request that triggered the regeneration.
export async function regenerateManifest(
  opts: RegenerateManifestOpts,
): Promise<void> {
  try {
    const text = await renderManifest(opts);
    await fsp.writeFile(path.join(opts.baseDir, "df.d.ts"), text, "utf8");
  } catch (err) {
    // eslint-disable-next-line no-console
    console.warn(
      `[manifest] regenerate failed: ${
        err instanceof Error ? err.message : String(err)
      }`,
    );
  }
}

// --- Rendering -------------------------------------------------------------

async function renderManifest(opts: RegenerateManifestOpts): Promise<string> {
  const { baseDir, tenantId } = opts;
  const resolver = new DiskLibraryResolver({ baseDir });
  const entries = await safeList(resolver, tenantId);

  // Partition into tools (frontmatter present) and primitives.
  const tools: ManifestEntry[] = [];
  const primitives: ManifestEntry[] = [];
  for (const e of entries) {
    const isTool = await detectTool(baseDir, tenantId, e.name);
    const description = isTool
      ? await readDescriptionFromFrontmatter(baseDir, tenantId, e.name)
      : null;
    const target = isTool ? tools : primitives;
    target.push({ name: e.name, spec: e.spec, description });
  }

  // Mount sources. Each registered mount exposes one `db.<ident>` per
  // collection it holds. We don't try to import the mount's synthesised
  // type here — the manifest references it by file path so the agent can
  // `cat` the typed module if it wants the row shape.
  const mounts = listMountCollections();

  const out: string[] = [];
  out.push("// Auto-generated by datafetch. Do not edit.");
  out.push(`// Tenant: ${tenantId}`);
  out.push(`// Regenerated: ${new Date().toISOString()}`);
  out.push("");
  out.push(SUPPORT_TYPES);
  out.push("");
  out.push("declare const df: {");
  out.push("  /**");
  out.push("   * Mounted dataset collections — substrate-rooted retrieval.");
  out.push("   * Each handle exposes the four-method retrieval contract:");
  out.push("   *   findExact, search, findSimilar, hybrid.");
  out.push("   */");
  out.push("  db: {");
  if (mounts.length === 0) {
    out.push("    // (no mounts registered)");
  } else {
    for (const m of mounts) {
      out.push(`    /** ${escapeJSDoc(m.summary)} */`);
      out.push(`    ${m.ident}: CollectionHandle;`);
    }
  }
  out.push("  };");
  out.push("");
  out.push(`  /** Library for tenant "${tenantId}". Tools first, then primitives. */`);
  out.push("  lib: {");

  if (tools.length > 0) {
    out.push("    // ─── Tools (intent-complete; call directly when description matches) ───");
    out.push("");
    for (const t of tools) {
      renderEntry(out, t, /* asTool */ true);
    }
  }
  if (primitives.length > 0) {
    if (tools.length > 0) out.push("");
    out.push("    // ─── Primitives (compose with) ───");
    out.push("");
    for (const p of primitives) {
      renderEntry(out, p, /* asTool */ false);
    }
  }
  if (tools.length === 0 && primitives.length === 0) {
    out.push("    // (no library functions yet)");
  }
  out.push("  };");
  out.push("");
  out.push("  /** Run an async function with df.* in scope; returns a Result envelope. */");
  out.push("  run<T>(fn: () => Promise<T>): Promise<Result<T>>;");
  out.push("};");
  out.push("");
  return out.join("\n");
}

function renderEntry(
  out: string[],
  entry: ManifestEntry,
  asTool: boolean,
): void {
  const inputType = renderInlineType((entry.spec as FnSpec<unknown, unknown>).input);
  // Output schema is informational only; the runtime always wraps in Result<T>.
  // Render `Result<unknown>` for the return type and let the JSDoc carry detail.
  const jsdoc = buildJSDoc(entry, asTool);
  for (const line of jsdoc) out.push(`    ${line}`);
  out.push(`    ${entry.name}(input: ${inputType}): Promise<Result<unknown>>;`);
  out.push("");
}

function buildJSDoc(entry: ManifestEntry, asTool: boolean): string[] {
  const lines: string[] = [];
  lines.push("/**");
  if (asTool && entry.description) {
    // Use the rich description from the wrapper's YAML frontmatter.
    for (const para of entry.description.split("\n")) {
      lines.push(` * ${para}`);
    }
  } else {
    lines.push(` * ${entry.spec.intent}`);
  }
  // Add an example call if the spec carries one — this is what gives the
  // model a concrete shape to mimic, not just a type signature.
  const example = entry.spec.examples?.[0];
  if (example !== undefined) {
    const inputJson = jsonOneLine(example.input);
    if (inputJson.length < 240) {
      lines.push(" *");
      lines.push(` * @example`);
      lines.push(` *   await df.lib.${entry.name}(${inputJson})`);
    }
  }
  lines.push(" */");
  return lines;
}

// --- Helpers ---------------------------------------------------------------

type ManifestEntry = {
  name: string;
  spec: FnSpec<unknown, unknown>;
  description: string | null;
};

async function safeList(
  resolver: DiskLibraryResolver,
  tenantId: string,
): Promise<{ name: string; spec: FnSpec<unknown, unknown> }[]> {
  try {
    return await resolver.list(tenantId);
  } catch {
    return [];
  }
}

function listMountCollections(): { ident: string; summary: string }[] {
  const reg = getMountRuntimeRegistry();
  const out: { ident: string; summary: string }[] = [];
  for (const r of reg.list()) {
    for (const m of r.identMap) {
      out.push({
        ident: m.ident,
        summary: `${r.mountId} / ${m.name}`,
      });
    }
  }
  return out;
}

async function detectTool(
  baseDir: string,
  tenantId: string,
  name: string,
): Promise<boolean> {
  const candidates = [
    path.join(baseDir, "lib", tenantId, `${name}.ts`),
    path.join(baseDir, "lib", "__seed__", `${name}.ts`),
  ];
  for (const file of candidates) {
    try {
      const head = await fsp.readFile(file, "utf8");
      const trimmed = head.slice(0, 32).trimStart();
      return trimmed.startsWith("/* ---") || trimmed.startsWith("/*---");
    } catch {
      // try the next candidate
    }
  }
  return false;
}

// Pull the `description: |` block out of the wrapper's YAML frontmatter.
// Best-effort; failures fall back to the spec's intent string.
async function readDescriptionFromFrontmatter(
  baseDir: string,
  tenantId: string,
  name: string,
): Promise<string | null> {
  const file = path.join(baseDir, "lib", tenantId, `${name}.ts`);
  let text: string;
  try {
    text = await fsp.readFile(file, "utf8");
  } catch {
    return null;
  }
  // Frontmatter is `/* --- ... --- */` at the top.
  const match = text.match(/\/\*\s*---\s*\n([\s\S]*?)\n\s*---\s*\*\//);
  if (!match || !match[1]) return null;
  const yaml = match[1];
  // Walk the YAML line-by-line: find `description: |`, then collect every
  // subsequent line whose indent is greater than the description key's
  // indent. Stop at the next column-zero key. Block-scalar parsing this
  // way avoids regex pitfalls with multiline YAML.
  const lines = yaml.split("\n");
  let i = 0;
  while (i < lines.length) {
    if (/^\s*description\s*:\s*\|\s*$/.test(lines[i]!)) break;
    i += 1;
  }
  if (i >= lines.length) return null;
  const body: string[] = [];
  for (let j = i + 1; j < lines.length; j += 1) {
    const line = lines[j]!;
    if (/^[a-zA-Z][a-zA-Z0-9_-]*\s*:/.test(line)) break; // next key
    body.push(line);
  }
  // Strip the leading common indent (block scalars typically use two
  // spaces); `trim` cleans up trailing blank lines.
  return body
    .map((l) => l.replace(/^ {0,4}/, ""))
    .join("\n")
    .trim() || null;
}

// Minimal valibot-schema → TypeScript-type renderer. Mirrors the inline
// renderer in src/cli/agentVerbs.ts; small enough to keep self-contained.
type SchemaShape = {
  type?: string;
  kind?: string;
  expects?: string;
  entries?: Record<string, SchemaShape>;
  item?: SchemaShape;
  wrapped?: SchemaShape;
  options?: unknown[];
  literal?: unknown;
};

function renderInlineType(schema: unknown): string {
  const s = schema as SchemaShape;
  if (!s || typeof s !== "object") return "unknown";
  switch (s.type) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "unknown":
    case "any":
      return "unknown";
    case "null":
      return "null";
    case "undefined":
      return "undefined";
    case "literal":
      return JSON.stringify(s.literal);
    case "picklist": {
      const opts = (s.options ?? []) as unknown[];
      return opts.map((o) => JSON.stringify(o)).join(" | ");
    }
    case "array": {
      const inner = s.item ? renderInlineType(s.item) : "unknown";
      return `${inner}[]`;
    }
    case "optional": {
      const inner = s.wrapped ? renderInlineType(s.wrapped) : "unknown";
      return inner.endsWith("?") ? inner : `${inner} | undefined`;
    }
    case "object": {
      const entries = s.entries ?? {};
      const fields = Object.entries(entries).map(([key, child]) => {
        const inner = renderInlineType(child);
        if (inner.endsWith(" | undefined")) {
          return `${key}?: ${inner.slice(0, -" | undefined".length)}`;
        }
        return `${key}: ${inner}`;
      });
      return `{ ${fields.join("; ")} }`;
    }
    default:
      return s.expects ?? "unknown";
  }
}

function escapeJSDoc(s: string): string {
  return s.replace(/\*\//g, "*\\/");
}

function jsonOneLine(value: unknown): string {
  try {
    return JSON.stringify(value);
  } catch {
    return "...";
  }
}

const SUPPORT_TYPES = `interface Result<T> {
  value: T;
  mode: "novel" | "interpreted" | "llm-backed" | "cache" | "compiled";
  cost: {
    tier: 0 | 1 | 2 | 3 | 4;
    tokens: { hot: number; cold: number };
    ms: { hot: number; cold: number };
    llmCalls: number;
  };
  provenance: {
    tenant: string;
    mount: string;
    functionName?: string;
    trajectoryId: string;
    pins: Record<string, string>;
  };
  escalations: number;
  warnings?: { code: string; message: string }[];
}

interface CollectionHandle {
  findExact(filter: Record<string, unknown>, limit?: number): Promise<unknown[]>;
  search(query: string, opts?: { limit?: number }): Promise<unknown[]>;
  findSimilar(query: string, limit?: number): Promise<unknown[]>;
  hybrid(query: string, opts?: { limit?: number }): Promise<unknown[]>;
}`;
