// df.d.ts manifest generator.
//
// Produces a TypeScript declaration file that lists every available `df.*`
// callable for a given tenant: collection handles from registered mounts,
// crystallised tools (with their YAML-frontmatter description as JSDoc),
// and seed/tenant primitives (with intent + schema as JSDoc).
//
// Mirrors the pattern Cloudflare Code Mode uses: instead of advertising
// tools as JSON descriptors and routing each call through the model,
// expose them as a typed code surface the model writes against. The
// signatures are denser and the model's TypeScript training prior does
// the heavy lifting on what each function does.
//
// Regeneration is cheap and idempotent. Called from /v1/connect (so the
// manifest reflects the active workspace at session boot) and from the
// observer's authoring path (so a freshly-crystallised tool appears
// immediately in the manifest the next caller reads).

import { promises as fsp } from "node:fs";
import path from "node:path";

import { getMountRuntimeRegistry } from "../adapter/runtime.js";
import { readFrontmatterHead } from "../sdk/frontmatter.js";
import type { FnSpec } from "../sdk/index.js";
import { renderSchemaInline } from "../sdk/schemaRender.js";
import { DiskLibraryResolver } from "../snippet/library.js";

// --- Public ----------------------------------------------------------------

export type RegenerateManifestOpts = {
  baseDir: string;
  tenantId: string;
};

// Write `<baseDir>/df.d.ts` reflecting the current workspace state.
// Best-effort: errors are swallowed and logged so a transient miss
// doesn't crash the request that triggered the regeneration.
//
// Idempotent: if the rendered content matches what's already on disk,
// the file is left alone (no inotify churn for downstream watchers).
export async function regenerateManifest(
  opts: RegenerateManifestOpts,
): Promise<void> {
  try {
    const text = await renderManifest(opts);
    const target = path.join(opts.baseDir, "df.d.ts");
    let existing: string | null = null;
    try {
      existing = await fsp.readFile(target, "utf8");
    } catch {
      // file missing → write
    }
    if (existing === text) return;
    await fsp.writeFile(target, text, "utf8");
  } catch (err) {
    // eslint-disable-next-line no-console
    console.warn(
      `[manifest] regenerate failed: ${
        err instanceof Error ? err.message : String(err)
      }`,
    );
  }
}

// --- Rendering -------------------------------------------------------------

async function renderManifest(opts: RegenerateManifestOpts): Promise<string> {
  const { baseDir, tenantId } = opts;
  const resolver = new DiskLibraryResolver({ baseDir });
  const entries = await safeList(resolver, tenantId);

  // Partition entries into tools (frontmatter present in the tenant
  // overlay) and primitives. One bounded read per entry.
  const annotated = await Promise.all(
    entries.map(async (e) => {
      const head = await readFrontmatterHead(
        path.join(baseDir, "lib", tenantId, `${e.name}.ts`),
      );
      return { name: e.name, spec: e.spec, description: head.description, isTool: head.isTool };
    }),
  );
  const tools = annotated.filter((e) => e.isTool);
  const primitives = annotated.filter((e) => !e.isTool);

  // Mount sources. Each registered mount exposes one `db.<ident>` per
  // collection it holds. The manifest references the synthesised typed
  // module by file path; the agent can `cat` it for the row shape.
  const mounts = listMountCollections();

  const out: string[] = [];
  out.push("// Auto-generated by datafetch. Do not edit.");
  out.push(`// Tenant: ${tenantId}`);
  out.push("");
  out.push(SUPPORT_TYPES);
  out.push("");
  out.push("declare const df: {");
  out.push("  /**");
  out.push("   * Mounted dataset collections — substrate-rooted retrieval.");
  out.push("   * Each handle exposes the four-method retrieval contract:");
  out.push("   *   findExact, search, findSimilar, hybrid.");
  out.push("   */");
  out.push("  db: {");
  if (mounts.length === 0) {
    out.push("    // (no mounts registered)");
  } else {
    for (const m of mounts) {
      out.push(`    /** ${escapeJSDoc(m.summary)} */`);
      out.push(`    ${m.ident}: CollectionHandle;`);
    }
  }
  out.push("  };");
  out.push("");
  out.push(`  /** Library for tenant "${tenantId}". Tools first, then primitives. */`);
  out.push("  lib: {");

  if (tools.length > 0) {
    out.push("    // ─── Tools (intent-complete; call directly when description matches) ───");
    out.push("");
    for (const t of tools) out.push(...renderEntry(t, /* asTool */ true));
  }
  if (primitives.length > 0) {
    if (tools.length > 0) out.push("");
    out.push("    // ─── Primitives (compose with) ───");
    out.push("");
    for (const p of primitives) out.push(...renderEntry(p, /* asTool */ false));
  }
  if (tools.length === 0 && primitives.length === 0) {
    out.push("    // (no library functions yet)");
  }
  out.push("  };");
  out.push("");
  out.push("  /** Run an async function with df.* in scope; returns a Result envelope. */");
  out.push("  run<T>(fn: () => Promise<T>): Promise<Result<T>>;");
  out.push("};");
  out.push("");
  return out.join("\n");
}

function renderEntry(entry: ManifestEntry, asTool: boolean): string[] {
  const inputType = renderSchemaInline(entry.spec.input, { optional: "union" });
  // Output schema is informational only; the runtime always wraps in Result<T>.
  // Render `Result<unknown>` for the return type and let the JSDoc carry detail.
  const lines = buildJSDoc(entry, asTool).map((l) => `    ${l}`);
  lines.push(`    ${entry.name}(input: ${inputType}): Promise<Result<unknown>>;`);
  lines.push("");
  return lines;
}

function buildJSDoc(entry: ManifestEntry, asTool: boolean): string[] {
  const lines: string[] = ["/**"];
  if (asTool && entry.description) {
    for (const para of entry.description.split("\n")) {
      lines.push(` * ${para}`);
    }
  } else {
    lines.push(` * ${entry.spec.intent}`);
  }
  // An example call gives the model a concrete shape to mimic, not just
  // a type signature. Bounded so a giant fixture doesn't bloat the file.
  const example = entry.spec.examples?.[0];
  if (example !== undefined) {
    const inputJson = jsonOneLine(example.input);
    if (inputJson.length < 240) {
      lines.push(" *");
      lines.push(` * @example`);
      lines.push(` *   await df.lib.${entry.name}(${inputJson})`);
    }
  }
  lines.push(" */");
  return lines;
}

// --- Helpers ---------------------------------------------------------------

type ManifestEntry = {
  name: string;
  spec: FnSpec<unknown, unknown>;
  description: string | null;
  isTool: boolean;
};

async function safeList(
  resolver: DiskLibraryResolver,
  tenantId: string,
): Promise<{ name: string; spec: FnSpec<unknown, unknown> }[]> {
  try {
    return await resolver.list(tenantId);
  } catch {
    return [];
  }
}

function listMountCollections(): { ident: string; summary: string }[] {
  const reg = getMountRuntimeRegistry();
  const out: { ident: string; summary: string }[] = [];
  for (const r of reg.list()) {
    for (const m of r.identMap) {
      out.push({ ident: m.ident, summary: `${r.mountId} / ${m.name}` });
    }
  }
  return out;
}

function escapeJSDoc(s: string): string {
  return s.replace(/\*\//g, "*\\/");
}

function jsonOneLine(value: unknown): string {
  try {
    return JSON.stringify(value);
  } catch {
    return "...";
  }
}

const SUPPORT_TYPES = `interface Result<T> {
  value: T;
  mode: "novel" | "interpreted" | "llm-backed" | "cache" | "compiled";
  cost: {
    tier: 0 | 1 | 2 | 3 | 4;
    tokens: { hot: number; cold: number };
    ms: { hot: number; cold: number };
    llmCalls: number;
  };
  provenance: {
    tenant: string;
    mount: string;
    functionName?: string;
    trajectoryId: string;
    pins: Record<string, string>;
  };
  escalations: number;
  warnings?: { code: string; message: string }[];
}

interface CollectionHandle {
  findExact(filter: Record<string, unknown>, limit?: number): Promise<unknown[]>;
  search(query: string, opts?: { limit?: number }): Promise<unknown[]>;
  findSimilar(query: string, limit?: number): Promise<unknown[]>;
  hybrid(query: string, opts?: { limit?: number }): Promise<unknown[]>;
}`;
