import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { schemaFingerprint, readWorkspaceManifest } from "./runtime.js";

export class DatafetchWorkspace {
  constructor(private readonly baseDir: string) {}

  async list(): Promise<string[]> {
    const manifest = await readWorkspaceManifest(this.baseDir);
    if (!manifest) {
      return [];
    }
    const collections = manifest.datasets.flatMap((dataset) =>
      dataset.collections.map((collection) => `/datafetch/db/${collection}.ts`)
    );
    return [...collections, ...(await this.listHookModules())];
  }

  async readFile(virtualPath: string): Promise<string> {
    const dbMatch = virtualPath.match(/^\/datafetch\/db\/([a-zA-Z0-9_-]+)\.ts$/);
    if (dbMatch) {
      return this.synthesizeCollectionModule(dbMatch[1]);
    }
    const hookMatch = virtualPath.match(/^\/datafetch\/hooks\/([a-zA-Z0-9_-]+)\/([a-zA-Z0-9_-]+)\.ts$/);
    if (hookMatch) {
      return this.synthesizeHookModule(hookMatch[1], hookMatch[2]);
    }

    const localPath = this.toWritableLocalPath(virtualPath);
    return readFile(localPath, "utf8");
  }

  async writeFile(virtualPath: string, content: string): Promise<void> {
    if (virtualPath.startsWith("/datafetch/db/")) {
      const error = new Error(`Cannot write read-only generated module ${virtualPath}`) as NodeJS.ErrnoException;
      error.code = "EACCES";
      throw error;
    }
    const localPath = this.toWritableLocalPath(virtualPath);
    await mkdir(path.dirname(localPath), { recursive: true });
    await writeFile(localPath, content, "utf8");
  }

  private async synthesizeCollectionModule(collection: string): Promise<string> {
    const rows = await this.loadCollectionRows(collection);
    const typeName = `${toPascalCase(collection)}Row`;
    const schema = inferSchema(rows);
    const discriminator = inferDiscriminator(rows);
    const fingerprint = schemaFingerprint(rows);
    const sample = rows.slice(0, 2);
    const rowTypeSource = discriminator
      ? renderDiscriminatedUnion(collection, typeName, discriminator, rows)
      : renderFlatType(typeName, schema);
    return `// Generated by AtlasFS DatafetchWorkspace.
// Collection: ${collection}

export const SCHEMA_VERSION = "${fingerprint}" as const;

/**
${sample.map((row) => ` * @example ${JSON.stringify(row)}`).join("\n")}
 */
${rowTypeSource}

export type CollectionPrimitive<T> = {
  findExact(filter: Partial<T>, limit?: number): Promise<T[]>;
  findSimilar(query: string, limit?: number): Promise<T[]>;
  search(query: string, opts?: { limit?: number }): Promise<T[]>;
  hybrid(query: string, opts?: { limit?: number }): Promise<T[]>;
};

export declare const ${collection}: CollectionPrimitive<${typeName}>;
`;
  }

  private async loadCollectionRows(collection: string): Promise<Array<Record<string, unknown>>> {
    const manifest = await readWorkspaceManifest(this.baseDir);
    if (!manifest) {
      throw new Error(`No AtlasFS workspace found at ${this.baseDir}`);
    }
    for (const dataset of manifest.datasets) {
      if (!dataset.collections.includes(collection)) {
        continue;
      }
      const file = path.join(this.baseDir, "data", dataset.id, `${collection}.jsonl`);
      return (await readJsonl(file)) as Array<Record<string, unknown>>;
    }
    throw new Error(`Unknown collection: ${collection}`);
  }

  private async synthesizeHookModule(domain: string, intentName: string): Promise<string> {
    const file = path.join(this.baseDir, "hooks", domain, `${intentName}.json`);
    const hook = JSON.parse(await readFile(file, "utf8")) as {
      name: string;
      intent: string;
      description: string;
      collections: string[];
      route: string[];
    };
    return `// hook · ${hook.name}
// intent: ${hook.intent}
// collections: ${hook.collections.join(", ")}

/**
 * ${hook.description}
 *
 * Suggested route:
${hook.route.map((step, index) => ` *   ${index + 1}. ${step}`).join("\n")}
 */
export interface ${toPascalCase(hook.intent)}Intent {
  question: string;
}
`;
  }

  private async listHookModules(): Promise<string[]> {
    const root = path.join(this.baseDir, "hooks");
    let domains: string[];
    try {
      domains = await readdir(root);
    } catch {
      return [];
    }
    const modules: string[] = [];
    for (const domain of domains) {
      let entries: string[];
      try {
        entries = await readdir(path.join(root, domain));
      } catch {
        continue;
      }
      for (const entry of entries.filter((file) => file.endsWith(".json"))) {
        modules.push(`/datafetch/hooks/${domain}/${entry.replace(/\.json$/, ".ts")}`);
      }
    }
    return modules.sort();
  }

  private toWritableLocalPath(virtualPath: string): string {
    const normalized = virtualPath.replace(/^\/+/, "");
    if (normalized.includes("..")) {
      throw new Error(`Invalid virtual path: ${virtualPath}`);
    }
    return path.join(this.baseDir, normalized.replace(/^datafetch\//, ""));
  }
}

function inferSchema(rows: Array<Record<string, unknown>>): Record<string, string> {
  const fields = new Map<string, Set<string>>();
  for (const row of rows) {
    for (const [key, value] of Object.entries(row)) {
      const types = fields.get(key) ?? new Set<string>();
      types.add(tsType(value));
      fields.set(key, types);
    }
  }
  return Object.fromEntries(
    Array.from(fields.entries()).map(([field, types]) => [field, Array.from(types).sort().join(" | ")])
  );
}

function renderFlatType(typeName: string, schema: Record<string, string>): string {
  return `export type ${typeName} = {
${Object.entries(schema).map(([field, type]) => `  ${field}: ${type};`).join("\n")}
};`;
}

function renderDiscriminatedUnion(
  collection: string,
  typeName: string,
  discriminator: string,
  rows: Array<Record<string, unknown>>
): string {
  const baseName = singularPascalCase(collection);
  const variants = new Map<string, Array<Record<string, unknown>>>();
  for (const row of rows) {
    const value = String(row[discriminator]);
    variants.set(value, [...(variants.get(value) ?? []), row]);
  }
  const variantSources = Array.from(variants.entries()).map(([value, variantRows]) => {
    const variantName = `${toPascalCase(value)}${baseName}`;
    const stats = inferFieldStats(variantRows);
    const fields = Object.entries(stats).map(([field, fieldStats]) => {
      const type = field === discriminator
        ? JSON.stringify(value)
        : Array.from(fieldStats.types).sort().join(" | ");
      return `  /** @presence ${presence(fieldStats.count, rows.length)} */\n  ${field}: ${type};`;
    });
    return `export type ${variantName} = {\n${fields.join("\n")}\n};`;
  });
  const unionNames = Array.from(variants.keys()).map((value) => `${toPascalCase(value)}${baseName}`);
  return `${variantSources.join("\n\n")}

export type ${typeName} = ${unionNames.join(" | ")};`;
}

function inferDiscriminator(rows: Array<Record<string, unknown>>): string | null {
  for (const candidate of ["kind", "type", "_t"]) {
    const values = rows.map((row) => row[candidate]);
    if (values.length === 0 || values.some((value) => typeof value !== "string")) {
      continue;
    }
    const unique = new Set(values);
    if (unique.size > 1 && unique.size <= Math.max(8, rows.length)) {
      return candidate;
    }
  }
  return null;
}

function inferFieldStats(rows: Array<Record<string, unknown>>): Record<string, { types: Set<string>; count: number }> {
  const fields: Record<string, { types: Set<string>; count: number }> = {};
  for (const row of rows) {
    for (const [key, value] of Object.entries(row)) {
      fields[key] ??= { types: new Set<string>(), count: 0 };
      fields[key].types.add(tsType(value));
      fields[key].count += 1;
    }
  }
  return fields;
}

function presence(count: number, total: number): string {
  return `${Math.round((count / total) * 100)}%`;
}

function tsType(value: unknown): string {
  if (typeof value === "string") return "string";
  if (typeof value === "number") return "number";
  if (typeof value === "boolean") return "boolean";
  if (Array.isArray(value)) return "unknown[]";
  if (value === null) return "null";
  return "Record<string, unknown>";
}

async function readJsonl(file: string): Promise<unknown[]> {
  const text = await readFile(file, "utf8");
  return text
    .split("\n")
    .filter(Boolean)
    .map((line) => JSON.parse(line) as unknown);
}

function toPascalCase(value: string): string {
  return value
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part.slice(0, 1).toUpperCase() + part.slice(1))
    .join("");
}

function singularPascalCase(value: string): string {
  return toPascalCase(value.endsWith("s") ? value.slice(0, -1) : value);
}
