// installSnippetRuntime — the boot-time wiring point for the snippet
// runtime, the disk library resolver, and the seed `/lib/__seed__/`
// shims.
//
// Idempotent: subsequent calls update the in-process LibraryResolver
// singleton with a fresh DiskLibraryResolver bound to the supplied
// baseDir, and re-mirror the seed shim files.
//
// Seed shim format
// ----------------
// Each seed file at `<repo>/seeds/lib/<name>.ts` is the canonical
// authored seed (uses `fn({...})` against `../../src/sdk/index.js`).
// `installSnippetRuntime` writes a thin re-export shim under
// `<baseDir>/lib/__seed__/<name>.ts` whose only line is something like
// `export { <name> } from "<absolute-path-to-repo>/seeds/lib/<name>.ts";`.
// The DiskLibraryResolver follows that re-export to the canonical file
// at import time. This keeps the resolver contract clean
// (`<baseDir>/lib/__seed__/<name>.ts` is the layered-lookup target)
// without breaking the seed file's relative imports back into `src/sdk`.

import { promises as fsp } from "node:fs";
import path from "node:path";

import { setLibraryResolver } from "../sdk/index.js";

import { defaultBaseDir, locateRepoSubdir } from "../paths.js";
import { DiskLibraryResolver } from "./library.js";
import { DiskSnippetRuntime } from "./runtime.js";

// --- Public surface ---------------------------------------------------------

export type InstallSnippetRuntimeOpts = {
  baseDir?: string;
  // Skip the seed shim mirror step. Useful for tests that supply their
  // own LibraryResolver via setLibraryResolver() afterwards.
  skipSeedMirror?: boolean;
};

export type InstallSnippetRuntimeResult = {
  baseDir: string;
  snippetRuntime: DiskSnippetRuntime;
  libraryResolver: DiskLibraryResolver;
};

export async function installSnippetRuntime(
  opts: InstallSnippetRuntimeOpts = {},
): Promise<InstallSnippetRuntimeResult> {
  const baseDir = opts.baseDir ?? defaultBaseDir();

  if (!opts.skipSeedMirror) {
    await mirrorSeedShims(baseDir);
  }

  const libraryResolver = new DiskLibraryResolver({ baseDir });
  setLibraryResolver(libraryResolver);
  const snippetRuntime = new DiskSnippetRuntime();

  return {
    baseDir,
    snippetRuntime,
    libraryResolver,
  };
}

// --- Seed shim mirror -------------------------------------------------------

async function mirrorSeedShims(baseDir: string): Promise<void> {
  const seedDir = await locateRepoSubdir(path.join("seeds", "lib"));
  if (!seedDir) {
    // eslint-disable-next-line no-console
    console.warn(
      "[snippet/install] could not locate seeds/lib/; df.lib.<seedName> will fall back to tenant-overlay only",
    );
    return;
  }

  const targetDir = path.join(baseDir, "lib", "__seed__");
  await fsp.mkdir(targetDir, { recursive: true });

  let entries: import("node:fs").Dirent[];
  try {
    entries = await fsp.readdir(seedDir, { withFileTypes: true });
  } catch {
    return;
  }

  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith(".ts")) continue;
    const name = entry.name.slice(0, -3);
    const srcAbs = path.join(seedDir, entry.name);
    const dst = path.join(targetDir, entry.name);
    // Re-export shim. `<srcAbs>` is an absolute on-disk path; ESM
    // `import ... from` accepts both absolute file paths and `file://`
    // URLs under Node, but TypeScript's NodeNext resolver prefers the
    // file URL form. The DiskLibraryResolver imports this shim through
    // `pathToFileURL(<dst>).href`, which yields a `file://` parent URL
    // against which the absolute `file://` href resolves cleanly.
    const sourceFileUrl = `file://${srcAbs.replace(/\\/g, "/")}`;
    const shim =
      `// Auto-generated by installSnippetRuntime — do not edit.\n` +
      `// Re-exports the canonical seed at ${srcAbs}.\n` +
      `export { ${name} } from "${sourceFileUrl}";\n`;
    await fsp.writeFile(dst, shim, "utf8");
  }
}
