// Per-mount README.md generator.
//
// Per `kb/prd/decisions.md` D-019: each mount auto-generates a README that
// describes what the dataset is, typical query patterns, schema highlights,
// and gotchas. Sits alongside the workspace-level `/AGENTS.md` and the
// per-function `man <fn>`.
//
// Token budget: ~400 tokens per mount, well under the legibility ceiling.

import type { MountDescriptor } from "../sdk/index.js";

export type ReadmeArgs = {
  mountId: string;
  substrate: string;
  collections: Array<{
    name: string;
    rows: number;
    descriptor: MountDescriptor;
    fingerprint: string;
    sampleSize: number;
  }>;
};

export function synthesizeReadme(args: ReadmeArgs): string {
  const lines: string[] = [];

  // --- Header --------------------------------------------------------------
  lines.push(`# ${args.mountId}`);
  lines.push("");
  lines.push(
    `Mounted dataset, substrate \`${args.substrate}\`. Auto-generated by the datafetch bootstrap pipeline; do not edit by hand.`,
  );
  lines.push("");

  // --- Collections table ---------------------------------------------------
  lines.push("## Collections");
  lines.push("");
  lines.push("| Collection | Rows | Kind | Polymorphic | Fingerprint |");
  lines.push("|---|---|---|---|---|");
  for (const c of args.collections) {
    const poly = c.descriptor.polymorphic_variants
      ? `yes (${c.descriptor.polymorphic_variants.length})`
      : "no";
    lines.push(
      `| \`${c.name}\` | ${c.rows} | ${c.descriptor.kind} | ${poly} | \`${shortHash(c.fingerprint)}\` |`,
    );
  }
  lines.push("");

  // --- Schema highlights ---------------------------------------------------
  lines.push("## Schema highlights");
  lines.push("");
  for (const c of args.collections) {
    lines.push(`### ${c.name}`);
    lines.push("");
    const required: string[] = [];
    const optional: string[] = [];
    const embeddable: string[] = [];
    const labels: string[] = [];
    for (const [field, fd] of Object.entries(c.descriptor.fields)) {
      if (fd.presence >= 0.95) required.push(field);
      else optional.push(field);
      if (fd.embeddable) embeddable.push(field);
      if (fd.role === "label") labels.push(field);
    }
    if (required.length > 0) {
      lines.push(`- **Required fields**: ${required.map(code).join(", ")}`);
    }
    if (optional.length > 0) {
      lines.push(`- **Optional fields**: ${optional.map(code).join(", ")}`);
    }
    if (embeddable.length > 0) {
      lines.push(
        `- **Embeddable text fields** (mean length > 200 chars): ${embeddable.map(code).join(", ")}`,
      );
    }
    if (labels.length > 0) {
      lines.push(
        `- **Categorical labels** (low cardinality): ${labels.map(code).join(", ")}`,
      );
    }
    if (c.descriptor.polymorphic_variants) {
      lines.push(
        `- **Polymorphic variants**: ${c.descriptor.polymorphic_variants
          .map((v) => `\`${v.name}\` (${(v.presence * 100).toFixed(0)}%)`)
          .join(", ")}`,
      );
    }
    lines.push("");
  }

  // --- Typical query patterns (boilerplate for MVP) -----------------------
  lines.push("## Typical query patterns");
  lines.push("");
  lines.push(
    `Read \`man <fn>\` for any function in \`/lib/\`, or run \`apropos <intent>\` to discover capabilities. The four-method retrieval contract on every collection:`,
  );
  lines.push("");
  lines.push("```ts");
  lines.push(
    `const exact = await df.db.${defaultCollName(args.collections)}.findExact({ /* filter */ }, 10);`,
  );
  lines.push(
    `const lex   = await df.db.${defaultCollName(args.collections)}.search("query", { limit: 5 });`,
  );
  lines.push(
    `const sim   = await df.db.${defaultCollName(args.collections)}.findSimilar("query", 5);`,
  );
  lines.push(
    `const both  = await df.db.${defaultCollName(args.collections)}.hybrid("query", { limit: 5 });`,
  );
  lines.push("```");
  lines.push("");

  // --- Gotchas -------------------------------------------------------------
  lines.push("## Gotchas");
  lines.push("");
  lines.push(
    "- **Sample-derived cardinality.** The `cardinality_estimate` per field is computed from the bootstrap sample, not the full collection. Treat it as a hint, not ground truth.",
  );
  if (args.collections.some((c) => c.descriptor.polymorphic_variants)) {
    lines.push(
      "- **Polymorphic shapes.** Some collections carry multiple shapes per row, distinguished by a low-cardinality discriminator field. The synthesised `<coll>.ts` uses a discriminated union; narrow before access.",
    );
  } else {
    lines.push(
      "- **Polymorphism check ran.** No discriminator field was found in the sample; the schema is treated as single-shape. Re-publish if the underlying shape changes.",
    );
  }
  lines.push(
    "- **MVP search.** `findSimilar` and `hybrid` currently delegate to lexical `search`. Vector recall (Voyage embeddings + `$rankFusion`) lands post-MVP.",
  );
  lines.push(
    "- **No drift detection.** Content-addressable pins and stale-pin escalation are deferred per scope; assume the mount is current.",
  );
  lines.push("");

  return lines.join("\n");
}

function shortHash(fingerprint: string): string {
  // "sha256:abcdef..." → "sha256:abcdef…"
  const idx = fingerprint.indexOf(":");
  const head = idx >= 0 ? fingerprint.slice(0, idx + 1) : "";
  const tail = idx >= 0 ? fingerprint.slice(idx + 1) : fingerprint;
  return head + tail.slice(0, 8) + (tail.length > 8 ? "…" : "");
}

function code(s: string): string {
  return `\`${s}\``;
}

function defaultCollName(collections: ReadmeArgs["collections"]): string {
  if (collections.length === 0) return "<collection>";
  return collections[0].name;
}
